### ISSUE TITLE
Cost Today N/A

### ISSUE THREAD

**Issue by danfulton72** [custom-components/sensor.owlintuition#6] opened 2018-12-18 15:53 UTC
I've got the component configured, reading values but the Cost Today is not pulling through.

Is there something else I need to configure, or should it just come through?

**Comment by glpatcern** [comment] 2018-12-18 21:59
Hi, are you using a "version 1" or a "version 2" OWL sensor? The code at the moment parses a v2 XML payload as this is the sensor I have, and in that case it should come through. Otherwise, @jchasey has a v1 OWL network and all his contributions to this component support v1 (but not sure the cost reporting is working for him).

**Comment by glpatcern** [comment] 2020-03-30 05:12
[As there seems to be some cleanup going on, I'm closing this issue because of no acivity. Please reopen if the issue is still outstanding]

**Closed by glpatcern** 2020-03-30 05:12 UTC
