### ISSUE TITLE
Since update Owl Sensors offline

### ISSUE THREAD

**Issue by wcavanagh** [custom-components/sensor.owlintuition#29] opened 2023-05-26 20:00 UTC
Hi,
After the last update I don't seem to get any data from any of my sensors.  I am monitoring P1 and P3 electric usage.  I have checked all settings and nothing changed here other than update of the integration. 

I see following in dashboard
Entity not available: sensor.owl_intuition_electricity_today_p1
Entity not available: sensor.owl_intuition_electricity_today_p3
Entity not available: sensor.owl_intuition_electricity_battery_level

**Comment by glpatcern** [comment] 2023-05-29 07:51
Hi, could you please try again with 1) latest HA core and 2) latest master? There have been a few code changes here because of changes in HA core, so chances are you had some inconsistent setup.

Also, if it does not work yet, could you please paste some logs?

**Comment by wcavanagh** [comment] 2023-05-29 07:58
Thank you, yes everything is on the latest versions.  How do I get you logs? Sorry never had to look at logs before.  Thanks again.

**Comment by glpatcern** [comment] 2023-05-29 11:27
The logs are to be found in HA core itself, you should look for a `home-assistant.log` file in your specific HA setup. You can find instructions on the HA documentation.

(Just in case, I merged a PR minutes before commenting here. Probably unrelated but that's the latest code)

**Comment by wcavanagh** [comment] 2023-05-29 19:15
Nothing in the log that would point to it.  I see only these
```
023-05-25 20:59:16.690 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 35 and 77
2023-05-25 20:59:16.744 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-25 20:59:16.744 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-25 20:59:16.745 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-25 20:59:16.746 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration heatmiserneo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-25 20:59:16.746 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-25 20:59:16.746 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration owlintuition which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Comment by wcavanagh** [comment] 2023-05-29 19:52
Interesting I now get this on a check of config

Configuration invalid!
Platform error sensor.owlintuition - Exception importing custom_components.owlintuition.sensor

**Comment by naser-ali** [comment] 2023-05-29 20:11
I'm unfortunately getting exactly the same, including the invalid config. For now I've gone back to a previous version of sensor.py which sort of fixes it. I have the latest version of home assistant. It was all working pretty well until the recent few updates, so perhaps some short term patch/reversal until then?

**Comment by wcavanagh** [comment] 2023-05-29 20:21
Awesome, Also just gone back to an older version of sensor.py and now all working again :)

**Comment by BertrumUK** [comment] 2023-05-29 21:01
can you share the version you rolled back to or post the older version here ?

**Comment by glpatcern** [comment] 2023-05-29 21:05
Yes, that would help identifying the problematic change by bisection. I suspect it's the new HA system that checks for all unit of measurements to be consistent - I got my system working at some point but I do see some warning myself now. I only run electricity sensors: I can try and infer what is missing, but I appreciate more logs from other setups as well.

**Comment by glpatcern** [comment] 2023-05-29 21:11
And with [this commit](https://github.com/custom-components/sensor.owlintuition/commit/efb8851c3961c34a84633fb853f87ea18b961000) I have no warnings any longer. But again feedback is welcome on sensors other than electricity ;-)

**Comment by BertrumUK** [comment] 2023-05-29 21:22
ok, rolling back to [this version ](https://github.com/custom-components/sensor.owlintuition/blob/ba609bc63ac3814b2cf09fa50d8b351a163e0fdc/custom_components/owlintuition/sensor.py) clears the errors and restores the sensors.

**Comment by glpatcern** [comment] 2023-05-29 21:22
OK, the latest master as of now is confirmed to work with no warnings/errors with my setup. More tests appreciated, in particular with hot water and/or multizone setups.

**Comment by BertrumUK** [comment] 2023-05-29 21:29
ok, the new commit works and with no errors on Electricity and Solar. Thank you @glpatcern

**Comment by naser-ali** [comment] 2023-05-29 21:42
Yep, all fixed. Thanks so much for the quick response.

**Comment by wcavanagh** [comment] 2023-05-30 09:49
Amazing, working great here too

**Comment by glpatcern** [comment] 2023-05-30 10:08
Very good, closing this issue then!

**Closed as completed by glpatcern** 2023-05-30 10:08 UTC
